REVOKE CREATE ON SCHEMA public FROM PUBLIC;
ALTER SCHEMA public OWNER TO signage_owner;

GRANT USAGE ON SCHEMA public TO signage_app;
GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA public
  TO signage_app;
GRANT USAGE, SELECT, UPDATE
  ON ALL SEQUENCES IN SCHEMA public
  TO signage_app;

ALTER DEFAULT PRIVILEGES
  FOR ROLE signage_owner
  IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO signage_app;
ALTER DEFAULT PRIVILEGES
  FOR ROLE signage_owner
  IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO signage_app;
