# Generated by Django 5.2.8 on 2026-06-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('playlist_max_entries', models.PositiveIntegerField(default=100)),
                ('playlist_max_duration_seconds', models.PositiveIntegerField(default=1800)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
