# Generated by Django 5.2.8 on 2026-06-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0002_platformsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('failures', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
