# Generated by Django 5.2.8 on 2026-06-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0003_loginthrottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='kiosk_pin_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='device',
            name='kiosk_pin_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
