# Generated by Django 5.2.8 on 2026-06-24 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0004_device_kiosk_pin_hash_device_kiosk_pin_reset_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=160)),
                ('firmware_version', models.CharField(max_length=100)),
                ('android_version', models.CharField(max_length=32)),
                ('test_date', models.DateField()),
                ('evidence_reference', models.CharField(help_text='Internal path or ticket containing photos, logs, and test notes.', max_length=255)),
                ('device_owner_lock_task_passed', models.BooleanField(default=False)),
                ('boot_on_power_passed', models.BooleanField(default=False)),
                ('screen_state_passed', models.BooleanField(default=False)),
                ('power_loss_path_passed', models.BooleanField(default=False)),
                ('playback_12h_passed', models.BooleanField(default=False)),
                ('image_aspect_passed', models.BooleanField(default=False)),
                ('cache_capacity_passed', models.BooleanField(default=False)),
                ('network_reconnect_passed', models.BooleanField(default=False)),
                ('interrupted_download_passed', models.BooleanField(default=False)),
                ('thermal_passed', models.BooleanField(default=False)),
                ('mounting_power_safety_passed', models.BooleanField(default=False)),
                ('kiosk_escape_resistance_passed', models.BooleanField(default=False)),
                ('device_time_change_passed', models.BooleanField(default=False)),
                ('remote_disable_reboot_passed', models.BooleanField(default=False)),
                ('factory_reset_revocation_passed', models.BooleanField(default=False)),
                ('approved_for_pilot', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-test_date', 'model_name'],
            },
        ),
    ]
