# Generated by Django 5.2.16 on 2026-08-31 20:01

from django.db import migrations, models


def set_image_duration_to_15_seconds(apps, schema_editor):
    apps.get_model("signage", "MediaAsset").objects.filter(kind="image").update(
        duration_ms=15_000
    )


def restore_image_duration_to_10_seconds(apps, schema_editor):
    apps.get_model("signage", "MediaAsset").objects.filter(kind="image").update(
        duration_ms=10_000
    )


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0016_device_management'),
    ]

    operations = [
        migrations.RunPython(
            set_image_duration_to_15_seconds,
            restore_image_duration_to_10_seconds,
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='duration_ms',
            field=models.PositiveIntegerField(default=15000),
        ),
    ]
